language: go
install: go get -v github.com/spf13/hugo
script:
- hugo
deploy:
  provider: gae
  keyfile: halfdanjdk-3bbf6a628ba9.json
  project: halfdanjdk
  default: true
  skip_cleanup: true
  on:
    branch: master
notifications:
  email:
    on_failure: always
before_install:
- openssl aes-256-cbc -K $encrypted_2c1700b95230_key -iv $encrypted_2c1700b95230_iv
  -in halfdanjdk-3bbf6a628ba9.json.enc -out halfdanjdk-3bbf6a628ba9.json -d
