baseurl             = "https://halfadanjdk.appspot.com/"
builddrafts         = true
canonifyurls        = true
contentdir          = "content"
languageCode        = "en-US"
layoutdir           = "layouts"
publishdir          = "public"
author              = "Jonas Jongejan"
title               = "Jonas Jongejan"
pygmentsuseclasses  = true
#disqusshortname     = "cocoaexamplesite" # Comment out to disable Disqus.
pluralizelisttitles = false
#googleAnalytics     = "UA-123-45"
theme = "cocoa"

[permalinks]
fixed = ":title/"
work  = "work/:slug/"

[params]
author       = "Jonas Jongejan"
cachebuster  = true # add the current unix timestamp in query string for cache busting css assets
dateform     = "Jan 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description  = "Don't panic"
email        = "jonas@halfdanj.dk"
faviconfile  = "img/leaf.ico"
github       = "//github.com/halfdanj"
highlightjs  = true
lang         = "en"
linkedin     = "//linkedin.com/in/jonas-jongejan-0b2778bb"
twitter      = "//twitter.com/halfdanj"
selfIntro    = "Creative Technologist, currently working at Google Creative Lab in New York" # appears in the site header when set to a non-empty string

# gravatar             = ""                # do not use in the same time as avatar
avatar                 = "img/profile.jpg" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
# highlightjslanguages = ["go"]            # additional languages not included in the "common" set

extracssfiles = [ "/css/override.css" ] # In your `static` directory, add/remove files as necessary.

