name: Broken Link Check

on:
  schedule:
    - cron: 0 0 1/5 * *
  repository_dispatch:
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.6.1
        with:
          args: https://halfdanj.dk
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # - name: Create Issue From File
      #   if: env.lychee_exit_code != 0
      #   uses: peter-evans/create-issue-from-file@v4
      #   with:
      #     title: Link Checker Report
      #     content-filepath: ./lychee/out.md
      #     labels: report, automated issue
