name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci
      - name: Build the app
        run: npm run build

      - name: Deploy
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: halfdanjdk
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          CLI: gcloud
        with:
          args: npm run deploy
